# Домашняя работа к уроку 7

## Введение в высшую математику

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Задание 1

Решите линейную систему:

$\left(
\begin{array}{cccc}
1 & 2 & 3\\
4 & 0 & 6\\
7 & 8 & 9\end{array}
\right)\cdot X = \left(\begin{array}{cccc}
12\\2\\1\end{array}\right)
$

In [12]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
D = np.linalg.det(A)
print(D)
R = np.linalg.matrix_rank(A)
print(R)
B = np.array([12, 2, 1])
X = np.linalg.solve(A, B)
print(X)

59.999999999999986
3
[-9.2         0.9         6.46666667]


### Задание 2

Найдите псевдорешение:

$x + 2y – z = 1$

$3x – 4y = 7$

$8x – 5y + 2z = 12$

$2x – 5z = 7$

$11x +4y – 7z = 15$

In [29]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
# Решение
result = np.linalg.lstsq(A, B, rcond=None)[0]
print(result)
# Проверка
print(np.dot(A,result))
# Первое значение очень сильно отличается от исходного.
# Невязка
print(np.dot(A,result) - B)

[ 1.13919353 -0.90498444 -0.9009803 ]
[ 0.23020495  7.03751834 11.83650981  6.78328855 15.21805313]
[-0.76979505  0.03751834 -0.16349019 -0.21671145  0.21805313]


В работе. Будет чуть позже.