# Домашняя работа к уроку 7

## Введение в высшую математику

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import scipy.linalg

### Задание 1

Решите линейную систему:

$\left(
\begin{array}{cccc}
1 & 2 & 3\\
4 & 0 & 6\\
7 & 8 & 9\end{array}
\right)\cdot X = \left(\begin{array}{cccc}
12\\2\\1\end{array}\right)
$

In [2]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
D = np.linalg.det(A)
print(D)
R = np.linalg.matrix_rank(A)
print(R)
B = np.array([12, 2, 1])
X = np.linalg.solve(A, B)
print(X)

59.999999999999986
3
[-9.2         0.9         6.46666667]


### Задание 2

Найдите псевдорешение:

$x + 2y - z = 1$

$3x - 4y = 7$

$8x - 5y + 2z = 12$

$2x - 5z = 7$

$11x + 4y - 7z = 15$

In [3]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
# Решение
result = np.linalg.lstsq(A, B, rcond=None)[0]
print(result)
# Проверка
print(np.dot(A,result))
# Первое значение очень сильно отличается от исходного.
# Невязка
print(np.dot(A,result) - B)

[ 1.13919353 -0.90498444 -0.9009803 ]
[ 0.23020495  7.03751834 11.83650981  6.78328855 15.21805313]
[-0.76979505  0.03751834 -0.16349019 -0.21671145  0.21805313]


### Задание 3

Сколько решений имеет линейная система:

$\left(
\begin{array}{cccc}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9\end{array}
\right)\cdot X = \left(\begin{array}{cccc}
12\\2\\1\end{array}\right)
$

Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 


In [4]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
D = np.linalg.det(A)
print(D)
R = np.linalg.matrix_rank(A)
print(R)
B = np.array([12, 2, 1])
X = np.linalg.solve(A, B)
print(X)

-9.51619735392994e-16
2
[ 2.83726777e+16 -5.67453553e+16  2.83726777e+16]


Системы вырожденная, решение тривиальное.

In [5]:
BB = np.array([B])
C = np.concatenate((A, BB.T), axis=1)
print(C)
R = np.linalg.matrix_rank(C)
print(R)

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]
3


Ранг исходной матрицы (2) и ранг расширенной матрицы (3) не совпадают, следовательно система не совместна.

In [6]:
B = np.array([1, 4, 7])
BB = np.array([B])
C = np.concatenate((A, BB.T), axis=1)
print(C)
R = np.linalg.matrix_rank(C)
print(R)
X = np.linalg.solve(A, B)
print(X)

[[1 2 3 1]
 [4 5 6 4]
 [7 8 9 7]]
2
[-0.225  2.45  -1.225]


### Задание 4

Вычислите LU-разложение матрицы:

$\left(
\begin{array}{cccc}
1 & 2 & 3\\
2 & 16 & 21\\
4 & 28 & 73\end{array}
\right)$

После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [7]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
D = np.linalg.det(A)
print(D)
R = np.linalg.matrix_rank(A)
print(R)
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

432.00000000000017
3
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [8]:
B = np.array([1, 2, 3])
result = np.linalg.solve(A, B)
print(result)

[ 1.01388889  0.03472222 -0.02777778]


В работе. Будет чуть позже.